### ISSUE TITLE
Indicate and implement that Indentation is canonically tabs-only

### ISSUE THREAD

**Issue by mindlace** [somebee/imba#39] opened 2016-01-10 19:08 UTC
The imba documentation does not indicate what constitutes valid indentation.

In discussion with @somebee there was agreement that it is tabs only.

Please document & adjust the lexer to only use tabs as indentation.

I'm looking through the lexer now to see if I can find where the lexer makes that decision.

**Comment by somebee** [comment] 2016-01-10 19:50
Thanks for filing. The lexer (and the rewriter) is *really* horrendous - it's the last remnants of the early coffeescript code base imba was forked from 4 years ago. If you cannot find your way around it I'll try to look at it tomorrow :)

**Comment by somebee** [comment] 2016-01-10 19:58
I can also modify [sublime-imba](http://github.com/somebee/sublime-imba) to highlight wrongful use of spaces.

**Comment by erlingur** [comment] 2016-01-11 14:12
Since Imba inspiration is Ruby, where 2 spaces is the generally agreed-upon indentation I would say that is a strong argument for spaces. Personally, I found this issue here on Github because I was Googling why the hell sublime-imba was marking my indentation as wrong and trying to find a fix for it.

Is imba-source really tab-only? That is a huge downside for me. I have absolutely everything as spaces only and going back and forth in the same project is not something I am interested in. Which would be sad since I really like the idea and look of Imba and see some awesome potential in it.

**Comment by somebee** [comment] 2016-01-11 15:48
The difference is that Imba is indentation based, where Ruby is not. Imho 2 spaces is too unclear, and it was a huge pita with coffeescript. The two options as I seem them is 4 spaces or tab. In the latter case you can use a width of 2/4/6/8 depending on your preference without dictating this for whoever else is contributing to the same code base. Spaces is easier due to lack of tab-width support in certain browser (yeah, it's the one you guessed), but I think tabs is generally cleaner. The main point brought forward here is that we should choose. And since the user base is (still, hopefully) so small - I think we should be okay with requiring tabs from the beginning. This is 2016, editors should be able to handle tabs by now?

**Comment by erlingur** [comment] 2016-01-12 09:34
No, but Python is.

I personally have a huge dislike of tabs. I use coffeescript and have not had any problems with indentation. I would argue that you should follow the target democratic you are aiming for with Imba. If you are aiming for Ruby developers then spaces is the "standard". If it's something else, then do that. It's your project, you can do what you want :)

But, as you know, this is a huge debate, tabs vs. spaces, VIM vs Emacs, etc. I would do my best to avoid it and try to support both if possible. Python just cares about the relative indentation, not the exact amount of indentation, that would be the best way IMO. I know that if something would force me to use tabs I just wouldn't use that thing in my projects. I'm sure a lot of people that love tabs and hate spaces feel the same way. I was really excited to use Imba :/

**Comment by somebee** [comment] 2016-01-12 09:51
Hmm, I always knew this would be hard :/ Are you just as okay with 4 spaces @mindlace?

>  Python just cares about the relative indentation, not the exact amount of indentation, that would be the best way IMO.

Isn't this the result of a very early decision that is almost impossible to back out of. If you asked the creators today I think they would want to force 4 spaces.

>  I know that if something would force me to use tabs I just wouldn't use that thing in my projects.

What environment are you using. I cannot really understand why people are *so* determined on either side. I can understand the frustration when people mix tabs and spaces etc, but isn't consistency by far the most important thing?

Even though my personal preference is tabs, I guess most developers (especially coming from ruby and coffee script) prefer spaces. I'm open for going for 4-spaces as the only valid option. A growing community is obviously more important than my preference here. What do you think @mindlace?

**Comment by erlingur** [comment] 2016-01-12 10:15
> What environment are you using. I cannot really understand why people are so determined on either side. I can understand the frustration when people mix tabs and spaces etc, but isn't consistency by far the most important thing?

I use ST3 and iTerm2 for most things, then the odd tool here and there. Yes, exactly, consistency. That's my main argument for 2 spaces. It doesnt matter what tool I use, what environment, browser, whatever. All my code will always have the exact same indentation no matter where I look at it. If would use tabs I would have to make sure all my tools properly show 1 tab as 2 spaces, which means going into configuration files and setting this up. That's fine for my box but when I'm debugging stuff on other servers, looking at diffs online, using other tools I often even can't choose what a tab looks like. And that drives me nuts.

2 spaces is ALWAYS 2 spaces, no matter where you look. A tab can sometimes mean 2 spaces, sometimes 4. So yes, I value consistency above all.

**Comment by erlingur** [comment] 2016-01-12 10:35
Found something interesting regarding this.

http://ukupat.github.io/tabs-or-spaces/

Ruby is 100% 2 spaces
Coffeescript is ~80% 2 spaces
CSS is ~72% 2 spaces
HTML is ~56% 2 spaces
Javascript is ~60% 2 spaces
Python is ~92% 4 spaces

https://news.ycombinator.com/item?id=10795745

Seems like you could just find the community you are most interested in and go with the convention they use :)

**Comment by somebee** [comment] 2016-01-12 10:36
Yes, I've used Ruby a lot, but Imba still uses significant whitespace, a thing I *really* like. I do think that being able to tell the indentation by glancing is more important with significant whitespace. Now I simply changed a setting in sublime to use 2 spaces for indentation for a while, and since we use tabs I didn't really need to alter any files. I don't fully understand why this is not considered a good thing?

**Comment by somebee** [comment] 2016-01-12 10:39
The early adopters will probably come from ruby and coffee script. But the syntax is very different as well, do you think a different indentation will make people not want to learn it? Is this really an important part of choosing a language?

**Comment by erlingur** [comment] 2016-01-12 10:51
Well, I can only speak from my own experience and say it made me **immediately** frustrated that I couldn't use the same convention for indentation for everything in my project. It really is important. Just look at the HUGE debates that have been about this point. If it wasn't important, people wouldn't be debating so much about it for SO long. Just read the comments on the HN thread I linked.

Significant whitespace is fine, forcing me to change the styleguide for my project is not. Oh, and also consider projects where styleguides are enforced and mandatory. For almost all Ruby places that styleguide says "2 spaces".

The absolute best would be to support both tabs and spaces, using just relative indentation like Python. If that was not possible I would say go with 2 spaces to conform to Ruby (if that's the demographic you want), third best would be forcing tabs (so you please both the tab people and Ruby people could make the editor show 2 spaces) and in last place would be 4 spaces I think.

**Comment by erlingur** [comment] 2016-01-12 11:08
I just saw your edit. Wait, can you currently choose between spaces and tabs? The sublime plugin highlighted 2 spaces as red for me so I assumed it wasn't possible.

Yes, my advice would be to stay as far away from the tabs vs. spaces debate as possible and support both if you can. If you can not support both I would support the one you suspect most of your developers will use. If that's Ruby, Python, Coffeescript or Javascript it seems that would mean spaces. If you need to choose the number of spaces I would again choose 2 as that seems the most poppular for those developers.

**Comment by somebee** [comment] 2016-01-12 11:08
> it made me immediately frustrated that I couldn't use the same convention for indentation for everything in my project.

What editor were you using? Imba currently supports what you describe as *"The absolute best"*. It compiles fine with both, and different sizes.

**Comment by erlingur** [comment] 2016-01-12 11:10
We are a bit out of sync here, both commenting at the same time :)

Well then, that's perfect. I would keep that if you possibly can! :+1: I was using ST3 :)

**Comment by somebee** [comment] 2016-01-12 11:12
The most important problem now is that it even allows mixing tabs and spaces in the same file.. And the highlighters don't have access to which is preferred in a specific file, so it's difficult to highlight wrongful indents.

**Comment by erlingur** [comment] 2016-01-12 12:34
Hmm. I would then skip the highlighting for now and rely on the parser to notify the user of wrongful indents until a better solution can be found. I'm sure someone else has found a solution to this. Maybe even a linter would be helpful? That could point to lines with the wrong indents?

**Comment by somebee** [comment] 2016-01-12 13:09
@erlingur I see now that the sublime plugin didn't really support highlighting with space indents. Pushed a [new version](https://github.com/somebee/sublime-imba) now which will probably be available through package manager in an hour or so. And imba (master branch) is updated to report an error when mixed/inconsistent indentation is encountered. If you have a license for Sublime Text, I'd recommend downloading the [dev version](http://www.sublimetext.com/3dev) since it has a better syntax format :)

**Comment by erlingur** [comment] 2016-01-12 13:13
@somebee Hey awesome, thanks! I'll update it and check it out :)

> And imba (master branch) is updated to report an error when mixed/inconsistent indentation is encountered.

Ok, that seems like a fair result, I like it.

> If you have a license for Sublime Text, I'd recommend downloading the dev version since it has a better syntax format :)

Ok, didn't know that. Yeah, I have a license, will definitely do that, thanks!

**Comment by unabst** [comment] 2016-01-12 14:42
Just to add, this debate here epitomizes what is considered "opinionated" in design. Design decisions should only be made where forced, as opposed to forcing users to accept your "opinion".

To support the most opinions is by far the winning-est scenario, so here it would be to have a setting where the coders can choose. This will be a positive feature with little downside apart from having to implement it. It would allow coders to migrate more easily, enjoy aligning their code to their personal opinions, and will also avoid any unnecessary debate. 

Of course, you should still state your opinion. The issue is with forcing it. So if you had a switch to turn on "Ruby style indentation" then Ruby fans will love you for it.

The problem with indentation is ultimately it doesn't matter that much. If one caused cancer, there would be no debate. Hence, opinions end up holding weight, and that is why it results in opinionated design if forced upon users.

**Comment by erlingur** [comment] 2016-01-12 15:46
Hey @somebee, I've updated Sublime and it's much better, thanks!

@unabst Yeah, I feel that the current resolution is really the best way to reduce friction and increase developer engagement. Kudos to @somebee :)

**Comment by mindlace** [comment] 2016-01-13 00:33
If the compiler accepts files with mixed tab and space indentation, logical changes can occur in the code even though nothing has changed except whitespace.

In my experience with python projects, this can be a pain to debug.

Arguing that you should be able to use the same indentation between different languages is like arguing you should be able to use the same syntax between languages.

Anyway, it's not a dealbreaker to me either way, I just think you'll ultimately be happier if you pick one indentation method and stick with it.

**Comment by erlingur** [comment] 2016-01-13 12:49
@mindlace That's why Imba will warn you if it sees mixed/inconsistent indentation.

> Arguing that you should be able to use the same indentation between different languages is like arguing you should be able to use the same syntax between languages.

I don't really agree with that but even if that's true, why is that so bad? Are you saying you **don't** want languages to have similar syntaxes? You want every language to have a completely different syntax?

**Comment by somebee** [comment] 2016-01-14 15:50
After much thought and valuable discussion (thanks for convincing me @erlingur), we'll keep allowing whatever style of indentation you want, but it *must* be consistent within each file. The compiler will now throw errors when it encounters inconsistent indentation. Closing it for now.

**Closed by somebee** 2016-01-14 15:50 UTC
Labels: enhancement

**Comment by erlingur** [comment] 2016-01-14 15:54
Awesome! :+1: :)

**Comment by unabst** [comment] 2016-01-16 03:01
Just to add to what @mindlace said...
>In my experience with python projects, this can be a pain to debug.

It certainly would as any freedom in coding practices always does...

> Arguing that you should be able to use the same indentation between different languages is like arguing you should be able to use the same syntax between languages.

I think this is a great opinion, but an opinion still because it is arguable. The problem with educated opinions is most of them are great. That is why there is no one right answer... hence supporting as many right answers as possible becomes the only way to maximize satisfaction across an arbitrary group, and excluding opinions leads to constraining the group. 

> Anyway, it's not a dealbreaker to me either way, I just think you'll ultimately be happier if you pick one indentation method and stick with it.

Indeed, @somebee would certainly be happy with only his preferred method of indentation and not having to implement what ultimately he would not use... It's just a matter of what he sees as the future of imba and whether he wishes to support various opinions and how opinionated or unopinionated he wishes to be. So it boils down to his philosophy, which of course he is free to choose since this is his project.

So I guess I'm just saying no one is wrong here, and it is up to @somebee :)
